### PR TITLE
Bugfix Computer without Camera

### PR DESCRIPTION
**Pull request by javierquevedo**
Fix an issue that would cause the GTK application to crash when opening the properties panel if the computer did not have a webcam

### CODE REVIEW

**Comment by kennethdick** [comment]
This is excellent change! We have webcams fail due to hardware and that causes application to be unusable although audio video hybrid call should now be possible.

**Comment by javierquevedo** [comment]
I'm glad that you find it interesting.
Let's hope they merge it!

**Comment by bagage** [comment]
Hi @javierquevedo, thanks for this PR 👍. I'd be glad to merge it but I need first you to sign [the contributor agreement](http://www.belledonne-communications.com/downloads/Belledonne_communications_CA.pdf) and sent me it back. 
Thanks!

**Comment by javierquevedo** [comment]
@bagage I am afraid that for now I am unable to sign the contributor agreement.
Since the code is so small and simple, I would suggest to close the merge request and perform a similar bugfix yourself. Let me know if that works, otherwise I will discuss signing the agreement as a independent developer as opposed to a developer part of a larger organization.

**Comment by Ri0n** [comment]
Thanks for the fix. I just added it to my Gentoo overlay.

```
diff --git a/gtk/propertybox.c b/gtk/propertybox.c
index 2b1e12c..9e35f3a 100644
--- a/gtk/propertybox.c
+++ b/gtk/propertybox.c
@@ -42,6 +42,7 @@ void linphone_gtk_fill_combo_box(GtkWidget *combo, const char **devices, const c
 		This dummy text needs to be removed first*/
 	}
 
+	if (p)
 	for(;*p!=NULL;++p){
 		if ( cap==CAP_IGNORE
 			|| (cap==CAP_CAPTURE && linphone_core_sound_device_can_capture(linphone_gtk_get_core(),*p))

```

**Pull request closed without merging**
