### PR TITLE
Fixes infinite loop since if call redirection fails the calls don't a…

### PR DESCRIPTION
**Pull request by Svalorzen**
…ctually get terminated.

### CODE REVIEW

**Comment by bagage** [comment]
Thanks @Svalorzen, glad to see you are still working with call redirection! Can you please indent using tabs and bracket on the same line, eg:
```C
if (cond) {
} else {
}
```

Thanks!

**Comment by Svalorzen** [comment]
Sure, I'll change it now.

 I actually wanted to ask, after this I wanted to make another patch to allow redirection of single calls by id (making the commands like redirect all <endpoint> or redirect <id> <endpoint>). Do you think it could be merged?

**Comment by bagage** [comment]
Sounds gound to me, so yes go ahead :)

**Comment by Svalorzen** [comment]
Should I continue in this pull request or wait for this to be merged and do another?

**Comment by bagage** [comment]
Can you create another branch please? I'll integrate that one soon but it should not block you in the mean time.

**Comment by bagage** [comment]
Merged in master.

**Pull request closed without merging**
